<?php namespace App\Models;

/**
 * Eloquent class to describe the blood_groups table
 *
 * automatically generated by ModelGenerator.php
 */
class BloodGroups extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'blood_groups';

    public $timestamps = false;

    protected $fillable = array('name');

    public function userProfiles()
    {
        return $this->hasMany('App\Models\UserProfiles', 'blood_group_id', 'id');
    }
}
