<?php namespace App\Models;

/**
 * Eloquent class to describe the category table
 *
 * automatically generated by ModelGenerator.php
 */
class Category extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'category';

    public $timestamps = false;

    protected $fillable = array('name');

    public function userProfiles()
    {
        return $this->hasMany('App\Models\UserProfiles', 'category_id', 'id');
    }

}

