<?php namespace App\Models;

/**
 * Eloquent class to describe the notifications table
 *
 * automatically generated by ModelGenerator.php
 */
class Notifications extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'notifications';

    public function getDates()
    {
        return array('emergency_date');
    }

    protected $fillable = array('title', 'details', 'type', 'emergency_status_id', 'emergency_date');

    public function users()
    {
        return $this->belongsTo('App\Models\Users', 'user_id', 'id');
    }
}
