<?php namespace App\Models;

/**
 * Eloquent class to describe the statuses table
 *
 * automatically generated by ModelGenerator.php
 */
class Statuses extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'statuses';

    public $timestamps = false;

    protected $fillable = array('status', 'type');

    public function events()
    {
        return $this->hasMany('App\Models\Events', 'status_id', 'id');
    }
}
