<?php namespace App\Models;

/**
 * Eloquent class to describe the user_profiles table
 *
 * automatically generated by ModelGenerator.php
 */
class UserProfiles extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'user_profiles';

    protected $fillable = array('name', 'address2', 'contacts', 'status','blood_group_id','address1','status');

    public function users()
    {
        return $this->belongsTo('App\Models\Users', 'user_id', 'id');
    }

    public function bloodGroups()
    {
        return $this->belongsTo('App\Models\BloodGroups', 'blood_group_id', 'id');
    }

    public function districts()
    {
        return $this->belongsTo('App\Models\Districts', 'address1', 'id');
    }
}
