<?php namespace App\Models;

/**
 * Eloquent class to describe the users table
 *
 * automatically generated by ModelGenerator.php
 */
class Users extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'users';

    protected $fillable = array('username', 'password', 'api_token', 'remember_token');

    public function roleUsers()
    {
        return $this->hasMany('App\Models\RoleUsers', 'user_id', 'id');
    }

    public function userProfiles()
    {
        return $this->hasMany('App\Models\UserProfiles', 'user_id', 'id');
    }

}

