<?php namespace App\Models;

/**
 * Eloquent class to describe the donation_histories table
 *
 * automatically generated by ModelGenerator.php
 */
class DonationHistories extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'donation_histories';

    public function getDates()
    {
        return array('donated_date');
    }

    protected $fillable = array('user_id', 'donated_date');

    public function users()
    {
        return $this->belongsTo('App\Models\Users', 'id', 'id');
    }
}
