<?php namespace App\Models;

/**
 * Eloquent class to describe the events table
 *
 * automatically generated by ModelGenerator.php
 */
class Events extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'events';

    public function getDates()
    {
        return array('date');
    }

    protected $fillable = array('title', 'details', 'location', 'date', 'duration');

    public function statuses()
    {
        return $this->belongsTo('App\Models\Statuses', 'status_id', 'id');
    }

    public function users()
    {
        return $this->belongsTo('App\Models\Users', 'user_id', 'id');
    }
}
