<?php namespace App\Models;

/**
 * Eloquent class to describe the users table
 *
 * automatically generated by ModelGenerator.php
 */
class Users extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'users';

    protected $fillable = array('username', 'email', 'password');

    public function donationHistories()
    {
        return $this->hasOne('App\Models\DonationHistories', 'id', 'id');
    }

    public function events()
    {
        return $this->hasMany('App\Models\Events', 'user_id', 'id');
    }

    public function notifications()
    {
        return $this->hasMany('App\Models\Notifications', 'user_id', 'id');
    }

    public function roleUsers()
    {
        return $this->hasMany('App\Models\RoleUsers', 'user_id', 'id');
    }

    public function userProfiles()
    {
        return $this->hasMany('App\Models\UserProfiles', 'user_id', 'id');
    }
}
